### ISSUE TITLE
bug with DISCO-L475VG-IOT01A

### ISSUE THREAD

**Issue by droussel3** [stm32duino/M24SR64-Y#2]
Hello

i try to use Dynamic NFC tag based on M24SR with its printed NFC antenna with
discovery L475VG-IOT01A.
There is a lot of error .
Thank you for issue

**Comment by fpistm** [comment]
Hi @droussel3 ,
could you describe more your issue.
STM32 core version?
sketch?
error log?
I've made some tests and all is ok.

**Comment by droussel3** [comment]
Hi @fpistm 
i update my core (2017.9.22)
so with core 2018.1.18 i have that
Arduino : 1.8.5 (Windows Store 1.8.10.0) (Windows 10), Carte : "Discovery, STM32L475VG-DISCOVERY-IOT, Mass Storage, Generic Serial, None, Smallest (-Os default)"

Le chemin d'accŠs sp‚cifi‚ est introuvable.

Le chemin d'accŠs sp‚cifi‚ est introuvable.

exit status 1
Erreur de compilation pour la carte Discovery

with last core 2017.11.24  i have no problem

Thank you

**Comment by fpistm** [comment]
Ok. It is not linked to the library. It was fixed in the git repository and will be available in the next release.
This is because there is space in path (Arduino installation path or user local Arduino path).
See: https://github.com/stm32duino/Arduino_Core_STM32/pull/204
