### ISSUE TITLE
Not compiling with IDE 1.8.5

### ISSUE THREAD

**Issue by hcostelha** [stm32duino/M24SR64-Y#3]
It fails to compile with the error "STM32duino_M24SR64-Y\src/Message.h:41:21: fatal error: algorithm: No such file or directory"

**Comment by fpistm** [comment]
Hi, you should tell us a bit more.

Which core you used?
STM core:
https://github.com/stm32duino/Arduino_Core_STM32
Or Roger's one:
https://github.com/rogerclarkmelbourne/Arduino_STM32
other?

algorithm is part of the arm gcc toolchain and there is no issue with STM core and arm gcc 6-2017-q2-update (installed with the core).

**Comment by hcostelha** [comment]
Hi,

Maybe I go this wrong, but looking to https://github.com/stm32duino/M24SR64-Y I got the ideia that this library was developed for Arduino to interact with the M24SR64-Y IC through I2C. I was testing it with the Arduino Mega2560.

Best regards,
Hugo

**Comment by fpistm** [comment]
Ok, that's what I think.
This library has been developed using the STM core (for STM32 MCU based on arm).
This lib uses algorithm provided by arm toolchain that is probably not provided for the Arduino Mega2560 by avr.
Don't know if avr support could be added.
Any thought about that @cparata ?

Anyway you should have a warning about library compatibility as it is tag for stm32?
https://github.com/stm32duino/M24SR64-Y/blob/fc2ba20bde1bf5e9fa2371f44ec8269e55f0e410/library.properties#L9

**Comment by cparata** [comment]
Hi all,
the M24SR64-Y library uses some templates from STL library, so for this reason it is compatible only with STM core toolchain that includes natively this support. I don't know if it is possible to add easily the STL support in AVR toolchain in order to manage correctly the M24SR64-Y library.
Best Regards,
Carlo

**Comment by fpistm** [comment]
Related to AVR toolchain.
