### ISSUE TITLE
Code size too large for ATTiny targets

### ISSUE THREAD

**Issue by michaesc** [stm32duino/M24SR64-Y#5]
Trying to use this library with AVR8 ISA MCUs like the common ATTiny85 fails, because the library was not written efficiently.

The solution to this problem is to either write concisely with code size in mind or selectively implement according to platform using ifdefs.

**Comment by fpistm** [comment]
Hi @michaesc 
this library was implemented for stm32 as specified in:
https://github.com/stm32duino/M24SR64-Y/blob/27e2585f926a74b0792ca11b730adff9843be84a/library.properties#L9
It is not designed for other platform especially a 8 bits one.
Anyway, any contribution are welcome, if you are able to provide a PR do not hesitate.

**Comment by fpistm** [comment]
As answered previously, this library is for STM32 based board.
